HIPP-1571: Extract API type
hmrc/integration-catalogue pull request #66
Opened 2024-10-07 13:29 UTC by victorarbuesmallada

2024-10-07 13:33 UTC, victorarbuesmallada commented on app/uk/gov/hmrc/integrationcatalogue/repository/MongoFormatters.scala
> +  trait EnumFormat[T] extends Format[T]
this is required so Scala 3 `enum` works with `play-json`

2024-10-07 15:41 UTC, PaulCDurham requested changes
You need to make some changes to IntegrationRepository, probably just after the domain and subdomain stuff around line 91. Then add some tests to check that the new attribute is actually persisted in MongoDb.

2024-10-07 15:41 UTC, PaulCDurham commented on app/uk/gov/hmrc/integrationcatalogue/models/common/models.scala
> +enum ApiType derives EnumFormat:
Why not do the enum in the same style as the rest of the project? Consistency is a good thing.

2024-10-07 15:41 UTC, PaulCDurham commented on app/uk/gov/hmrc/integrationcatalogue/parser/oas/OASParserService.scala
> +      autopublish: Boolean,
Do we care? The validation we need to do is based on platform type. The Jira ticket doesn't mention it only being done when called by autopublish.

2024-10-07 15:41 UTC, PaulCDurham commented on app/uk/gov/hmrc/integrationcatalogue/repository/MongoFormatters.scala
> +  trait EnumFormat[T] extends Format[T]
If we do the enums in a consistent way then we don't need this

2024-10-07 15:59 UTC, victorarbuesmallada commented on app/uk/gov/hmrc/integrationcatalogue/models/common/models.scala
> +enum ApiType derives EnumFormat:
oh, I thought since Scala 3 comes with them maybe we'd like to go with that, will go back to what we have already

2024-10-07 16:00 UTC, victorarbuesmallada commented on app/uk/gov/hmrc/integrationcatalogue/parser/oas/OASParserService.scala
> +      autopublish: Boolean,
I've asked @edgarjimenez regarding that because the ticket mentions this:
```
The new field should NOT be added to the Admin API. Only to the backend endpoint used by the auto-publisher
```
We decided to only care about this field when the autopublish calls the API, happy to have a discussion around that.

2024-10-07 16:24 UTC, PaulCDurham commented on app/uk/gov/hmrc/integrationcatalogue/models/common/models.scala
> +enum ApiType derives EnumFormat:
It's just consistency. If you think there is a better way to do enums then raise a ticket and then let's maybe change all of them at the same time. Then we have a better, consistent pattern.

2024-10-08 09:09 UTC, edgarjimenez commented on app/uk/gov/hmrc/integrationcatalogue/parser/oas/OASParserService.scala
> +      autopublish: Boolean,
@victorarbuesmallada I know we decided to validate whether the call comes from the autopublisher, but I think @PaulCDurham makes a good point. We shouldn't care about where the call comes from, but more about the platform type. If the platform type is HIP, then we make sure the api-type is present.

2024-10-08 13:23 UTC, PaulCDurham approved these changes

2024-10-08 13:26 UTC, merged